const val KOTLIN_VERSION = "1.5.10"
const val KTOR_VERSION = "1.6.0"
const val COROUTINES_VERSION = "1.5.0-native-mt"
const val SERIALIZATION_VERSION = "1.2.1"
const val MORDANT_VERSION = "2.0.0-beta2"
const val CLIKT_VERSION = "3.2.0"
