const val KOTLIN_VERSION = "1.4.31"
const val KTOR_VERSION = "1.5.2"
const val COROUTINES_VERSION = "1.4.3-native-mt"
const val KOTLIN_CLI_VERSION = "0.3.1"
const val MORDANT_VERSION = "2.0.0-mpp"
const val SWIFT_PACKAGE = "2.0.0"
